# MIT LICENSE | https://opensource.org/licenses/MIT
# This theme 'Jekyll-theme' was created by [Stephen Tseng](https://www.ynewtime.com).
# This theme is pure jekyll theme so you don't need to use bundle
# Instead, just run 'jekyll serve', then visit 127.0.0.1:4000 to check your site offline.

title: JUN
email: 15817204807@163.com
description: >- # this means to ignore newlines until "baseurl:"
  周围是那么宁静，天空是那么蔚蓝。
  只有突突的心跳，淡淡的脸红在支配宇宙。
  ---《温柔的防浪石堤》
baseurl: "jun_blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: gelia.james
github_username:  geliaddd

# the navigation bar, you can create your own one
navigations: 
  - title: Archive
    class: fa fa-list-ul
    href: /archive
  - title: Tags
    class: fa fa-tags
    href: /tags
  - title: About
    class: fa fa-user
    href: /about
  - title: Telegram # if you don't have a telegram account, you can just delete this section
    class: fa fa-telegram
    href: //t.me/Ynewtime_Biki
  - title: Twitter # if you don't have a twitter account, you can just delete this section
    class: fa fa-twitter
    href: //twitter.com/Ynewtime
  - title: Subscribe # if you don't want to enable RSS, you can just delete this section
    class: fa fa-rss
    href: /atom.xml

# Build settings, you don't need to change this
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true
exclude: ["README.md"]